# Generated by Django 5.1.3 on 2024-12-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Deleted', 'Deleted'), ('Restored', 'Restored')], default='Restored', max_length=20),
        ),
    ]
